version: '3.5'
services:
  postgres:
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5439:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      DB_URI: "postgresql://postgres:postgres@postgres:5432/url_shortener"
    command: "sh -c 'alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 80'"